### ISSUE TITLE
Cannot find module '/appium/scripts/autoinstall-extensions.js'

### ISSUE THREAD

**Issue by mendozamiche** [moatazeldebsy/bitrise-step-appium-server#1]
With the change to install the `next` version, this error is coming up:

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/1036286/203651189-22e7a1a3-2d2c-43c7-a3c2-f91866f4e896.png">

I've specified a version instead but adding this issue here for awareness.

**Comment by moatazeldebsy** [comment]
Hi @mendozamiche, which stack are you using? I tried it on macOS VM and Ubuntu and it works fine. 

<img width="852" alt="Screenshot 2022-11-24 at 09 58 22" src="https://user-images.githubusercontent.com/45570191/203737881-36737dd4-e660-4809-b947-a1185596da18.png">

<img width="754" alt="Screenshot 2022-11-24 at 09 56 36" src="https://user-images.githubusercontent.com/45570191/203738076-942cddb0-2f38-43e5-ab1a-50cf6bb9c7c9.png">
<img width="1372" alt="Screenshot 2022-11-24 at 10 01 05" src="https://user-images.githubusercontent.com/45570191/203739351-61538dd2-403e-48a7-b66f-fa17dce9ef63.png">

**Comment by mendozamiche** [comment]
It's on an ubuntu as well `Android & Docker, on Ubuntu 20.04 Elite`. I wonder if it has to do with the node version being used?

**Comment by wr-lhiggitt** [comment]
I've also been having this problem. 

Stack: Android & Docker, on Ubuntu 20.04
Node: 16

EDIT: I've also change the node version to the same I'm using on my laptop (16.16.0) and can confirm it still has the same error.

**Comment by moatazeldebsy** [comment]
I didn't change the Node version I'm using the default one I tried the Step on Elite VM and also works fine for me 

This is the node version and npm version 

```
+ node -v
v16.19.0
+ npm -v
9.2.0
```
<img width="784" alt="Screenshot 2023-02-03 at 09 51 48" src="https://user-images.githubusercontent.com/45570191/216554812-20397eae-e922-4321-bafd-342a823b3ef2.png">
<img width="835" alt="Screenshot 2023-02-03 at 09 46 35" src="https://user-images.githubusercontent.com/45570191/216553833-8a91312d-235d-4d12-92e5-49eec1a8edf4.png">
<img width="1080" alt="Screenshot 2023-02-03 at 09 46 43" src="https://user-images.githubusercontent.com/45570191/216553845-96f2c16c-566d-4776-baf4-ca7ba6ea6394.png">

**Comment by orafaaraujo** [comment]
Hello, 

I'm also facing this issue using the Linux stack. 

Does anyone find some solution?

Thank you

**Comment by sidferreira** [comment]
@moatazeldebsy having this issue as well, only in Linux. Working fine on Mac.
